# Generated by Django 4.2 on 2025-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('cis', '0019_alter_classsection_co_reqs_alter_customuser_email_and_more'),
        ('pd_event', '0002_event_meta_alter_event_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='courses',
            field=models.ManyToManyField(to='cis.course'),
        ),
    ]
