# Generated by Django 4.2 on 2025-03-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0019_alter_classsection_co_reqs_alter_customuser_email_and_more'),
        ('pd_event', '0003_event_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='course_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cis.teachercoursecertificate'),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('highschool', 'High School'), ('faculty', 'Faculty')], default='instructor', max_length=50),
        ),
    ]
