# Generated by Django 4.2 on 2025-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_event', '0004_eventattendee_course_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_per_attendee',
            field=models.FloatField(default=0.0, null=True, verbose_name='Cost Per Attendee'),
        ),
    ]
