# Generated by Django 4.2 on 2025-07-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        # ('cis', '0171_alter_highschoolapplicationcoursereview_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pd_event', '0006_venue_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessions', models.ManyToManyField(related_name='info_sessions', to='pd_event.event')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
            options={
                'ordering': ['-term__code'],
            },
        ),
        migrations.CreateModel(
            name='InfoSessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('info_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_event.infosession')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSessionAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('info_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pd_event.infosession')),
            ],
        ),
    ]
