# Generated by Django 4.2 on 2025-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_event', '0007_infosession_infosessionnote_infosessionattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infosession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
