# Generated by Django 4.2 on 2025-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_event', '0008_infosession_description_infosession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosession',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
