# Generated by Django 4.2 on 2025-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_event', '0009_infosession_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosessionattendee',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
