# Generated by Django 4.2 on 2025-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd_event', '0010_infosessionattendee_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='ctle_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
